version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - cd vue_helloworld/
      - npm install
      - npm run build
artifacts:
  files:
    - vue_helloworld/dist/**/*
    - Scripts/*
    - appspec.yml
    